### PR TITLE
Improvement of app

### PR DESCRIPTION
**Pull request by mmojgani77**
- some refactor code and bug fixes
- performance improved in initial load

### CODE REVIEW

**Review by lovettchris — CHANGES_REQUESTED** [review]
Thanks, but I can't see the real changes from the formatting changes, so I just pushed a big reformat change to all of XmlNotepad so that you can merge that and then I will be able to see any real changes you made here.

**Comment by mmojgani77** [comment]
> Thanks, but I can't see the real changes from the formatting changes, so I just pushed a big reformat change to all of XmlNotepad so that you can merge that and then I will be able to see any real changes you made here.

I did merge that sir.

**Comment by mmojgani77** [comment]
> > Thanks, but I can't see the real changes from the formatting changes, so I just pushed a big reformat change to all of XmlNotepad so that you can merge that and then I will be able to see any real changes you made here.
> 
> I did merge that sir.

**Comment by mmojgani77** [comment]
> > > Thanks, but I can't see the real changes from the formatting changes, so I just pushed a big reformat change to all of XmlNotepad so that you can merge that and then I will be able to see any real changes you made here.
> > 
> > 
> > I did merge that sir.

some of additional white spaces is just because of my vs configs
but the others are code

**Pull request closed without merging**
